services:
  postgres:
    image: postgres:latest
    container_name: mydockerpotgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ozorninbd
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network
    ports:
      - "5430:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "ozorninbd"]
      interval: 10s
      timeout: 5s
      retries: 5

  python-app:
    build: ./app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: ozorninbd
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
    networks:
      - my_network
    ports:
      - "8000:8000"

networks:
  my_network:

volumes:
  pg_data:
